[pytest]
addopts = -n 1 --tb=short --cov=api --cov=utils --cov-report=term --cov-report=html --alluredir=reports/allure-results
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: 冒烟测试用例